# Generated by Django 4.1.2 on 2022-11-06 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=1000)),
                ("logo", models.ImageField(upload_to="app/Post/")),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("Created_by", models.CharField(blank=True, max_length=200)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="app/Post/")),
                ("content", models.TextField(max_length=1000)),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("Created_by", models.CharField(blank=True, max_length=200)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="IntroMadrasa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=1000)),
                ("full_image", models.ImageField(upload_to="app/Post/")),
                ("logo", models.ImageField(upload_to="app/Post/")),
                ("color_one", models.CharField(max_length=200)),
                ("color_two", models.CharField(max_length=200)),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("Created_by", models.CharField(blank=True, max_length=200)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Openions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("profile_pic", models.ImageField(upload_to="app/Post/")),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(max_length=1000)),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("Created_by", models.CharField(blank=True, max_length=200)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Targets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=1000)),
                ("image", models.ImageField(upload_to="app/Post/")),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("Created_by", models.CharField(blank=True, max_length=200)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("profile_pic", models.ImageField(upload_to="app/Post/")),
                ("phone_no", models.IntegerField()),
                ("position", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=200)),
                ("created_date", models.DateField(auto_now_add=True, null=True)),
                ("updated_date", models.DateField(auto_now=True)),
                ("Created_by", models.CharField(blank=True, max_length=200)),
                ("updated_by", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="SocialAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=800)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.teachers",
                    ),
                ),
            ],
        ),
    ]
